export const SETTING_UPDATE_INTERFACE_VALUE = 'SETTING_UPDATE_INTERFACE_VALUE';
export const SETTING_UPDATE_CLOCK_VALUE = 'SETTING_UPDATE_CLOCK_VALUE';
export const SETTING_UPDATE_CTRL_ENTER_VALUE = 'SETTING_UPDATE_CTRL_ENTER_VALUE';
export const SETTING_UPDATE_LANGUAGE_VALUE = 'SETTING_UPDATE_LANGUAGE_VALUE';
export const SETTING_RESET = 'SETTING_RESET';

export const MESSAGE_UPDATE_UNREAD = 'MESSAGE_UPDATE_UNREAD'
export const MESSAGE_CLEAN_UNREAD = 'MESSAGE_CLEAN_UNREAD'
export const MESSAGE_SAVE = 'MESSAGE_SAVE'
export const MESSAGE_UPDATE_USERNAME = 'MESSAGE_UPDATE_USERNAME'

export const USER_SAVE_USERNAME = 'USER_SAVE_USERNAME'

export const SOCKETIO_SAVE = 'SOCKETIO_SAVE'
