export const SETTING_UPDATE_INTERFACE_VALUE = 'SETTING_UPDATE_INTERFACE_VALUE';
export const SETTING_UPDATE_CLOCK_VALUE = 'SETTING_UPDATE_CLOCK_VALUE';
export const SETTING_UPDATE_CTRL_ENTER_VALUE = 'SETTING_UPDATE_CTRL_ENTER_VALUE';
export const SETTING_RESET = 'SETTING_RESET';

export const MESSAGE_SAVE = 'MESSAGE_SAVE'

export const USER_SAVE_USERNAME = 'USER_SAVE_USERNAME'
